name: "[CI] Continuous Integration"

# Sempre que tiver um commit ou um PR for aberto
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      ## [Common_CI_Steps]
      - uses: actions/checkout@v3
      ## =============
      - name: "Install dependencies"
        run: "npm ci"
      - name: "Lint"
        run: "npm run lint"
  test:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
      options: --user 1001
    steps:
      - uses: actions/checkout@v4
      - name: "Install dependencies"
        run: "npm ci"
      - name: "E2E tests"
        run: "npm run test"
